### ISSUE TITLE
The posts have no tag in the URL - won't open links properly

### ISSUE THREAD

**Issue by dreemsteem** [helpienaut/helpienaut.github.io#4]
I noticed that all of the URLs of the links are missing the initial tags

so...https://steemit.com/monkeesnap/@iamjadeline/t2y498v9

is actually listed as 
https://steemit.com/@iamjadeline/t2y498v9

This does not allow any of the links to be opened.  Gives an error message.

Thanks!

**Comment by eonwarped** [comment]
Was probably a temporary issue with steemit. It works now
