### ISSUE TITLE
'Download' button appears, but clicking has no effect

### ISSUE THREAD

**Issue by thekittygirl** [helpienaut/helpienaut.github.io#5]
Scrolled to the bottom, clicked the 'Download' button but nothing happens. Tried with OPERA and FIREFOX browsers in Windows-10/64-bit, latest versions of all software. Thanks!

**Comment by eonwarped** [comment]
Is this still happening?

**Comment by thekittygirl** [comment]
I had not tried it since reporting the error, then forgot about it. I just tried it again a moment ago. When I click the "Fetch" button, I get the message: "Error while loading" and nothing else happens. HOWEVER, I have found another solution that works for me, so I don't need this any more. However, others might still find it useful. Thanks for the reply!

**Comment by eonwarped** [comment]
If you have another solution I can link to it as well so people can be forwarded appropriately.

**Comment by eonwarped** [comment]
Oh oops. I broke it since I replied first. Reverted that change.

**Comment by thekittygirl** [comment]
> If you have another solution I can link to it as well so people can be forwarded appropriately.

The other solution is for Hive posts, not Steem posts. However, since all Steem posts were brought-over when Hive launched, that's not a problem for me! The other tool is by witness/dev @sn0n:  [https://blokz.github.io/hive-downloader](https://blokz.github.io/hive-downloader) and it works beautifully with the Markdown-viewer software called 'Notable' which is mentioned in this post:  [https://peakd.com/hive-169321/@sn0n/announcing-a-new-hive-tool-export-your-posts-to-zip](https://peakd.com/hive-169321/@sn0n/announcing-a-new-hive-tool-export-your-posts-to-zip)

**Comment by eonwarped** [comment]
Great thanks! Will reference and close this issue.

**Comment by thekittygirl** [comment]
Thank you again!
