### ISSUE TITLE
Create a post with all of the links

### ISSUE THREAD

**Issue by moeknows** [helpienaut/helpienaut.github.io#7]
I would like to be able to copy all of the markdown links so that I can easily make a post with direct links to all of my posts. Many people are being censored, but their posts are still accessible if you have direct links. I want to be able to send them to a place that allows for that. 

This would also help facilitate the creation of libraries similar to the way @creatr does on his posts.

**Comment by JtFried55** [comment]
Was there ever an answer to this? I got all my files in the spring of 2020, but one of my friends and others in the Terminal Discord server wanted to know how.
I googled it, came up with a post that had the Github link and instructions, but it is not working

**Comment by eonwarped** [comment]
I think this specific issue was actually resolved but never closed, there is an option to show markdown links
