### ISSUE TITLE
The link to retrieve all your steemit posts from the past doesn't seem to be working now

### ISSUE THREAD

**Issue by JtFried55** [helpienaut/helpienaut.github.io#8]
I got all my files in the Spring of 2020, used that download of .txt files for the first time today.

Some people asked me how I did it, but I didn't remember, so I googled it, and found a link posted last year with the github link
Helpienaut ``https://helpienaut.github.io/steem/allposts.html``
With SOME instructions, but that link doesn't seem to be working for anyone who has tried it today.

**Comment by eonwarped** [comment]
Should work now. This points to a hive node so it will have posts on steemit prior to the hive hard fork.

To get steem posts even after , I need to change the API node to api.steemit.com , but not sure how many people want that. Would need to add  a url parameter or checkbox option for that

**Comment by eonwarped** [comment]
Ack. using hive endpoint doesn't work, now it's the reverse, it only will work on steemit posts, not hive
